name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Compile check
        run: cargo check --locked

      - name: Format check
        run: cargo fmt --check

      - name: Lint check
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test

  msrv:
    name: MSRV Check (1.88.0)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust 1.88.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.88.0"

      - name: Cache Cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: cargo check
        run: cargo check --locked
